[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci", "cd client && npm ci"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "node server/index.js" 